name: Sync Fork

on:
  schedule:
    - cron: "*/5 * * * *" # every 30 minutes
  workflow_dispatch: # on button click
  push:
    branches:
      - sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        run: gh repo sync git@github.com:adanaja/e3-core.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
